mkupdater/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('updater.urls',namespace="updater")),

]

updater/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView


app_name = 'updater'
urlpatterns = [
    url(r'^$', login_required(views.index), name='index'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^signup/$', login_required(views.signup), name='signup'),
    url(r'^changeUser/$', login_required(views.UserUpdate.as_view(template_name='updater/changeUser.html')), name='changeUser'),
    url(r'^changePWD/$', login_required(views.changePWD), name='changePWD'),
    url(r'^info/$', login_required(TemplateView.as_view(template_name='updater/information.html')), name='info'),
    url(r'^infoaccept/$', login_required(views.infoaccept), name='infoaccept'),
    # url(r'^settings/$', login_required(views.settings), name='settings'),
    url(r'^(?P<item_id>[0-9]+)/(?P<user_id>[0-9]+)/refresh/$', login_required(views.refresh), name='refresh'),
    url(r'^(?P<user_id>[0-9]+)/sessionIntouch/$', login_required(views.getSessionIntouch), name='sessionIntouch'),
    url(r'^(?P<user_id>[0-9]+)/sessionUnitClub/$', login_required(views.getSessionUnitClub), name='sessionUnitClub'),

]

updater/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class UpdateHistory(models.Model):
    userID = models.IntegerField()
    itemID = models.IntegerField()
    date = models.DateTimeField('date published')
    
    def __str__(self):
        return "Item {} updated from {} at {}".format(str(self.itemID),str(self.userID),self.date)

class Item(models.Model):
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    filepath = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class LoginNames(models.Model):
    userID = models.IntegerField()
    inTouch = models.CharField(max_length=200)
    unitClub = models.CharField(max_length=200)

updater/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

class UpdateProfile(forms.ModelForm):
    username = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

    def clean_email(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError('Diese Email Adresse ist bereits in Benutzung. Bitte gib eine andere ein.')
        return email

updater/views.py
from __future__ import unicode_literals

import datetime
import io
import json
import os
import requests

import updater.utils as utils

from django.views.generic.edit import UpdateView

from .forms import UpdateProfile
from .models import LoginNames
from .models import UpdateHistory

from bs4 import BeautifulSoup
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone

    # 0 - MonthlySales
    # 1 - LadderOfSuccessPreviousQuarter
    # 2 - TeamAnalysisSales
    # 3 - RecruitersCommission
    # 4 - LadderOfSuccessCurrentQuarter
    # 5 - PeopleAndAdresses
    # 6 - InTouchSession
    # 7 - UnitClub
    
# Timeout for requests in seconds 
TIMEOUT = 60

def getSessionIntouch(request,user_id):

    item_id = 6
    loginload = {
        'txtConsultantID': request.POST.get('username'),
        'txtPassword': request.POST.get('password'),
        '__EVENTTARGET': 'btnSubmit'
    }

    try: 
        loginName = LoginNames.objects.get(userID = int(user_id) )
        loginName.inTouch = request.POST.get('username')
        loginName.save()
        print('Saved new login name for Intouch for user {}'.format(user_id))
    except:
        new = LoginNames(userID=int(user_id), inTouch=request.POST.get('username'))
        new.save()     
        print('New Intouch LoginName created for user {}'.format(user_id))
   

    print(loginload)
    cookieIntouchPath = 'cookieIntouch.dat'

    userpath = os.path.join(settings.BASE_DIR,'updater','files',str(user_id))
    if not os.path.isdir(userpath):
            os.makedirs(userpath)

    BackGroundInput = dict()

    # return HttpResponseRedirect(reverse('updater:index'))

    with requests.session() as c:
        # get the start cookies of the session
        try:
            html = c.get(utils.startURLIntouch, timeout = TIMEOUT)
        except requests.exceptions.Timeout:
            messages.error(request, 'In Touch reagiert leider nicht. Bitte versuche \
                                        es später noch einmal oder schreibe eine Mail an support@lennartduschek.de!')
            return HttpResponseRedirect(reverse('updater:index'))

        soup = BeautifulSoup(html.text, "lxml")

        # find all inputs to submit even the hidden ones
        for elem in soup.find('form').find_all('input', type='hidden'):
            BackGroundInput[elem['id']] = elem['value']

        # login to site with loginload as POST data
        # print('Login in to MaryKay Intouch')

        BackGroundInput.update(loginload)
        response = c.post(utils.loginUrlIntouch, data=BackGroundInput)
        hiddenResponse = c.get(utils.startURLIntouch)
        BackGroundInput.clear()

        if '.ASPXAUTH' in c.cookies.keys():
            # print(c.cookies['.ASPXAUTH'])
            utils.save_cookies(c.cookies,os.path.join(userpath, cookieIntouchPath))
            # print('saved cookies')
            cookieIntouch = c.cookies
            b = UpdateHistory(userID=int(user_id), itemID=item_id, date=timezone.now())
            b.save()
            messages.info(request, 'Login war erfolgreich!')

        else: 
            messages.error(request, 'Login hat nicht funktioniert!')
            # print('Login hat nicht funktioniert!')

    return HttpResponseRedirect(reverse('updater:index'))

def getSessionUnitClub(request,user_id):

    try: 
        loginName = LoginNames.objects.get(userID = int(user_id))
        loginName.unitClub = request.POST.get('username')
        loginName.save()
        print('Saved new login name for unit Club for user {}'.format(user_id))
    except:
        new = LoginNames(userID=int(user_id), unitClub=request.POST.get('username'))
        new.save()   
        print('New Unit Club LoginName created for user {}'.format(user_id))
     

    userpath = os.path.join(settings.BASE_DIR,'updater','files',str(user_id))
    if not os.path.isdir(userpath):
            os.makedirs(userpath)

    # Unit-Club
    loginload = {
        'uid': request.POST.get('username'),
        'pwd': request.POST.get('password')
    }
    cookieUnitClubPath = 'cookieUnitClub.dat'

    loginUrl = 'http://www.unit-club.net/up/unitclub/_login.php?' 
    # return HttpResponseRedirect(reverse('updater:index'))

    with requests.session() as c:
        # log in to website and get all the cookies
        print('getting new session')
        try:
            loginResponse = c.post(loginUrl, data=loginload, timeout = TIMEOUT)
        except requests.exceptions.Timeout:
            messages.error(request, 'Der Unit Club reagiert leider nicht. Bitte versuche \
                                        es später noch einmal oder schreibe eine Mail an support@lennartduschek.de!')
            return HttpResponseRedirect(reverse('updater:index'))

        soup = BeautifulSoup(loginResponse.text, "lxml")
        mydivs = soup.findAll("span", { "class" : "errormeldung" })

        if mydivs:
            print('Login nicht korrekt')
            messages.error(request, 'Login hat nicht funktioniert!')
        else:
            print('Login korrekt')
            messages.info(request, 'Login war erfolgreich!')
            cookieUnitClub = c.cookies
            print('Saving Cookie')
            utils.save_cookies(cookieUnitClub, os.path.join(userpath, cookieUnitClubPath))
            item_id = 7
            b = UpdateHistory(userID=int(user_id), itemID=item_id, date=timezone.now())
            b.save()

    return HttpResponseRedirect(reverse('updater:index'))

def logout_view(request):
    logout(request)
    return render(request, 'registration/logout.html')

def index(request):

    current_user = request.user
    s = User.objects.get(id=current_user.id)

    if not s.last_login:
        return render(request, 'updater/information.html')

    content = {}

    try:
        loginNames = LoginNames.objects.get(userID=current_user.id)
        print('Got one')
        print(loginNames)
    except:
        print('Got None')
        loginNames = ''
    
    content['loginNames'] = loginNames
    updateTime = [0 for x in range(8)]

    for kk in range(8):
        tmpTime =  UpdateHistory.objects.order_by('-date').filter(userID=request.user.id,itemID=kk)
        if not tmpTime:
            updateTime[kk] = 0
            continue
        t = timezone.now()-tmpTime[0].date
        s = t.total_seconds()

        if (kk == 6) or (kk == 7):
            if s > 10800:
                updateTime[kk] = False
                continue
        updateTime[kk] = '{}:{}:{}'.format(int(s // 3600), int(s % 3600 // 60), int(s % 60))

    content['updateTime'] = updateTime
    # print(content)
    return render(request, 'updater/index.html', content)

def refresh(request,item_id,user_id):

    itemID = int(item_id)
    print(user_id)
    print(itemID)
    print('Updating {}'.format(utils.CallingName[itemID]))

    if int(itemID) <= 3:

        try:
            inTouchRest(request,user_id,itemID)
            # print('Uploading {}'.format(utils.CallingName[itemID]))
            unitClubUpload(request,user_id,itemID)
            b = UpdateHistory(userID=int(user_id), itemID=int(item_id), date=timezone.now())
            b.save()
            messages.info(request, 'Aktualisierung war erfolgreich!')
        except:
            messages.error(request, 'Aktualisierung ist leider fehlgeschlagen!')

    elif itemID==4:
        try:
            # print('Downloading Erfolgsleiter aktuelles Quartal')
            inTouchLadderofSuccess(request,user_id)
            # print('Uploading Erfolgsleiter aktuelles Quartal')
            unitClubUpload(request,user_id,itemID)
            b = UpdateHistory(userID=int(user_id), itemID=int(item_id), date=timezone.now())
            b.save()
            messages.info(request, 'Aktualisierung war erfolgreich!')
        except:
            messages.error(request, 'Aktualisierung ist leider fehlgeschlagen!')

    elif itemID==5:
        try:
            print('Uploading Adressen und Karriereleiter')
            inTouchPeopleAndAdresses(request,user_id)
            unitClubUpload(request,user_id,itemID)
            b = UpdateHistory(userID=int(user_id), itemID=int(item_id), date=timezone.now())
            b.save()
            messages.info(request, 'Aktualisierung war erfolgreich!')
        except:
            messages.error(request, 'Aktualisierung ist leider fehlgeschlagen!')


    return HttpResponseRedirect(reverse('updater:index'))

def infoaccept(request):
    #Puts current date in for new user

    current_user = request.user
    s = User.objects.get(id=current_user.id)
    s.last_login = timezone.now()
    s.save()

    return render(request, 'updater/index.html')

def changePWD(request):
    # If yout want to change the password
    if request.method == 'POST':
        formPasswd = PasswordChangeForm(request.user, request.POST)
        if formPasswd.is_valid():
            user = formPasswd.save()
            update_session_auth_hash(request, user)  # Important!
            print('Changing password')
            messages.info(request, 'Dein Passwort wurde erfolgreich geändert!')
            return redirect('updater:changePWD')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        formPasswd = PasswordChangeForm(request.user)

    return render(request, 'updater/changePWD.html', {
        'formPasswd': formPasswd,
    })

def signup(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

updater/templates/updater/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="An updater that helps automate a task">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no">
        <title>Unit Club Updater</title>
        <!-- Add to homescreen for Chrome on Android -->
        <meta name="mobile-web-app-capable" content="yes">
        <link rel="icon" sizes="192x192" href="{% static 'updater/images/android-desktop.png' %}">
        <!-- Add to homescreen for Safari on iOS -->
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-title" content="Unit-Club-Updater">
        <link rel="apple-touch-icon-precomposed" href="{% static 'updater/images/ios-desktop.png' %}">
        <!-- Tile icon for Win8 (144x144 + tile color) -->
        <!--         <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
        <meta name="msapplication-TileColor" content="#3372DF"> -->
        <link rel="shortcut icon" href="{% static 'updater/images/favicon.png' %}">
        <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
        <!--
        <link rel="canonical" href="http://www.example.com/">
        -->
        <link rel="stylesheet" href="{% static 'updater/materialize/css/materialize.min.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <!-- <link rel="stylesheet" href="{% static 'updater/css/style.css' %}"> -->
        <script type="text/javascript" src="{% static '/updater/js/staystandalone.js' %}"></script>
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="{% static 'updater/materialize/js/materialize.js' %}"></script>
        <style>
        body {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
        }
        main {
        flex: 1 0 auto;
        }
        body {
        background: #fff;
        }
        .divider
        {
        margin-top: 3em;
        margin-bottom: 3em;
        }
        </style>
        {% block navbar %}
        {% endblock %}
    </head>
    <body>
        <!-- Dropdown Structure -->
        <ul id="dropdown1" class="dropdown-content indigo">
            <li><a class="white-text" href="{% url 'updater:changePWD' %}"><i class="material-icons">vpn_key</i></a></li>
            <li><a class="white-text" href="{% url 'updater:changeUser' %}"><i class="material-icons">perm_identity</i></a></li>
        </ul>
        <nav>
            <div class="nav-wrapper indigo">
                <a href="#!" class="brand-logo"></a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-down">
                    <li><a href="{% url 'updater:index' %}"><i class="material-icons">home</i></a></li>
                    <li><a href="{% url 'updater:info' %}"><i class="material-icons">info</i></a></li>
                    <li><a class="dropdown-button" href="{% url 'updater:index' %}" data-activates="dropdown1" ><i class="material-icons">settings arrow_drop_down</i></a></li>
                    <li><a href="{% url 'updater:logout' %}"><i class="material-icons">power_settings_new</i></a></li>
                </ul>
                <ul class="side-nav" id="mobile-demo">
                    <li><a href="{% url 'updater:index' %}">Startseite<i class="material-icons">home</i></a></li>
                    <li><a href="{% url 'updater:info' %}">Anleitung<i class="material-icons">info</i></a></li>
                    <li><a href="{% url 'updater:changeUser' %}">Einstellungen<i class="material-icons">settings</i></a></li>
                    <div class="divider"></div>
                    <li><a href="{% url 'updater:logout' %}">Logout<i class="material-icons">power_settings_new</i></a></li>
                </ul>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
        <script type="text/javascript">$( document ).ready(function(){
        $(".dropdown-button").dropdown();
        $(".button-collapse").sideNav();

        });</script>
    </body>
    <footer class = "page-footer indigo">
        <p class = "center white-text"> made by <a class="white-text" href="mailto:mail@lennartduschek.de"> Lennart Duschek </a>(2017)</p>
    </footer>
    {% block footer %}
    {% endblock %}
</html>

updater/templates/updater/changePWD.html
{% extends 'updater/base.html' %}
{% block content %}
    <main>
    <center>
    <div class="section"></div>
    <h4 class="black-text">Passwort ändern</h4>
    <div class="section"></div>
    <div class="container">
        <div id = "UpdateView" class="row">
            <div class="z-depth-1 grey lighten-4 col xl6 offset-xl3 l6 offset-l3 m6 offset-m3 s12" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">
                <form class="" action="" method="post">{% csrf_token %}
                    {{ formPasswd.as_p }}
                    <div class='row'>
                        <input type="submit" name="changePassword" onClick = "hideSelection()" class="col s12 btn waves-effect indigo" value="Update" />
                    </div>
                </form>
            </div>
        </div>
        <div class="container center">
            <div id = "spin" class="preloader-wrapper big">
                <div class="spinner-layer spinner-blue-only">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div><div class="gap-patch">
                    <div class="circle"></div>
                </div><div class="circle-clipper right">
                <div class="circle"></div>
            </div>
        </div>
    </div>
</div>
</center>
</main>
<script type="text/javascript">
function hideSelection(){
$( "#UpdateView" ).addClass( "hide" );
showSpinner();
}
function showSpinner(){
$( "#spin" ).addClass( "active" );
}
function hideSpinner(){
$( "#spin" ).removeClass( "active" );
}
</script>
<script type="text/javascript">$( document ).ready(function(){
{% if messages %}
{% for message in messages %}
{% if 'info' in message.tags %}
Materialize.toast( '{{ message }}' , 3000) // 4000 is the duration of the toast
{%endif%}
{% endfor %}
{% endif %}
});
</script>
{% endblock %}

updater/templates/updater/changeUser.html
{% extends 'updater/base.html' %}
{% block content %}
    <main>
    <center>
    <div class="section"></div>
    <h4 class="black-text">Nutzerdaten verändern</h4>
    <div class="section"></div>
    <div class="container">
        <div id = "UpdateView" class="row">
            <div class="z-depth-1 grey lighten-4 col xl6 offset-xl3 l6 offset-l3 m6 offset-m3 s12" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">
                <form class="" action="" method="post">{% csrf_token %}
                    {{ form.as_p }}
                    <div class='row'>
                        <input type="submit" onClick = "hideSelection()" class="col s12 btn waves-effect indigo" value="Update" />
                    </div>
                </form>
            </div>
        </div>
        <div class="container center">
            <div id = "spin" class="preloader-wrapper big">
                <div class="spinner-layer spinner-blue-only">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div><div class="gap-patch">
                    <div class="circle"></div>
                </div><div class="circle-clipper right">
                <div class="circle"></div>
            </div>
        </div>
    </div>
</div>
</center>
</main>
<script type="text/javascript">
function hideSelection(){
$( "#UpdateView" ).addClass( "hide" );
showSpinner();
}
function showSpinner(){
$( "#spin" ).addClass( "active" );
}
function hideSpinner(){
$( "#spin" ).removeClass( "active" );
}
</script>
<script type="text/javascript">$( document ).ready(function(){
{% if messages %}
{% for message in messages %}
{% if 'info' in message.tags %}
Materialize.toast( '{{ message }}' , 3000) // 4000 is the duration of the toast
{%endif%}
{% endfor %}
{% endif %}
});
</script>

{% endblock %}

updater/templates/updater/index.html
{% extends 'updater/base.html' %}
{% block content %}
    <main>
    <center>
    {% if user.is_authenticated %}
        <h4>Hallo {{ user.username }} !</h4>
    {% else %}
        <p> Not authenticated </p>
    {% endif %}
    </center>
    {% if messages %}
        {% for message in messages %}
            <!-- Modal Structure -->
            <div id="ErrorModal" class="modal">
                <div class="modal-content red">
                    <h5 class="white-text" >  Error</h5>
                    {% if 'error' in message.tags %}
                    <ul class="white-text">{{ message }}</ul>
                {% endif %}
                <i class="material-icons">warning</i>
            </div>
            <div class="modal-footer red">
                <a href="/" class="modal-action modal-close waves-effect waves-green btn-flat white-text">Okay</a>
            </div>
        </div>
    {% endfor %}
{% endif %}
<div class="row">
    <div id ="login" class="col xl4 offset-xl4 l6 offset-l3 m6 offset-m3 s12">
        <ul class="collapsible" data-collapsible="accordion">
            <li>
                <div class="collapsible-header hoverable"><i class="material-icons">system_update_alt</i>
                    <div><span class = "left-align">InTouch</span>
                    {% if updateTime.6 %}
                        <span class = "right-align"> | {{updateTime.6}} (h:mm:ss)</span>
                    {% endif %}
                </div>
            </div>
            <div class="collapsible-body ">
                <div class="row">
                    <form action="{% url 'updater:sessionIntouch' user.id %}" class="col s12" method="post">
                        {% csrf_token %}
                        <div class='row'>
                            <div class='input-field col s12'>
                                <input class='validate' type='text' name='username' id='username' value = "{{loginNames.inTouch}}" placeholder="Nutzername" >
                            </div>
                        </div>
                        <div class='row'>
                            <div class='input-field col s12'>
                                <input class='validate' type='password' name='password' id='password' placeholder="Passwort" />
                            </div>
                        </div>
                        <br />
                        <center>
                        <div class='row'>
                            <button onclick="hideSelection()" type='submit' name='btn_login' class='col s12 btn btn-medium waves-effect indigo'>Login</button>
                        </div>
                        </center>
                    </form>
                </div>
            </div>
        </li>
        <li>
            <div class="collapsible-header hoverable"><i class="material-icons">system_update_alt</i><span class = "">Unit Club</span>
            {% if updateTime.7 %}
                <span class = "right-align"> | {{updateTime.7}} (hh:mm:ss)</span>
            {% endif %}</div>
            <div class="collapsible-body ">
                <div class="row">
                    <form action="{% url 'updater:sessionUnitClub' user.id %}" class="col s12" method="post">
                        {% csrf_token %}
                        <div class='row'>
                            <div class='input-field col s12'>
                                <input class='validate' type='text' name='username' id='username' value = "{{loginNames.unitClub}}" placeholder="Nutzername" />
                            </div>
                        </div>
                        <div class='row'>
                            <div class='input-field col s12'>
                                <input class='validate' type='password' name='password' id='password' placeholder="Passwort" />
                            </div>
                        </div>
                        <br />
                        <center>
                        <div class='row'>
                            <button onclick="hideSelection()" type='submit' name='btn_login' class='col s12 btn btn-medium waves-effect indigo'>Login</button>
                        </div>
                        </center>
                    </form>
                </div>
            </div>
        </li>
    </ul>
</div>
</div>
{% if updateTime.6 and updateTime.7 %}
<div id = "firstDivider" class="divider"></div>
<div class="container">
    <div class="row">
        <div class="col m8 offset-m2 s12">
            <p id="info" class="center flow-text" >Klicke auf die Buttons um die entsprechenden Seiten zu aktualisieren. Die Aktualisierung kann sehr lange dauern.</p>
        </div>
    </div>
    <div class="row">
        <div id = "selection" class="collection col m8 offset-m2 s12 z-depth-1">
            <a onclick="hideSelection()" href="{% url 'updater:refresh' item_id=5 user_id=user.id %}" class="collection-item black-text">Adressen und Karrierestufen | {{updateTime.5}}</a>
            <a onclick="hideSelection()" href="{% url 'updater:refresh' item_id=0 user_id=user.id %}" class="collection-item black-text">Monats-Umsatz | {{updateTime.0}}</a>
            <a onclick="hideSelection()" href="{% url 'updater:refresh' item_id=2 user_id=user.id %}" class="collection-item black-text">Team-Umsatz | {{updateTime.2}}</a>
            <a onclick="hideSelection()" href="{% url 'updater:refresh' item_id=3 user_id=user.id %}" class="collection-item black-text">Team-Provision | {{updateTime.3}}</a>
            <a onclick="hideSelection()" href="{% url 'updater:refresh' item_id=4 user_id=user.id %}" class="collection-item black-text">Erfolgsleiter aktuelles Quartal | {{updateTime.4}}</a>
            <a onclick="hideSelection()" href="{% url 'updater:refresh' item_id=1 user_id=user.id %}" class="collection-item black-text">Erfolgsleiter vergangenes Quartal | {{updateTime.1}}</a>
        </div>
    </div>
</div>
{% else %}
<center>
<container>
<div class = "row">
    <div class = "col m8 offset-m2 s12">
        <p class="flow-text"> Um deine Seiten aktualisieren zu können musst du dich erst bei InTouch und dem Unit Club anmelden</p>
    </div>
</div>
</container>
</center>
{% endif %}
<div class="container center">
<div id = "spin" class="preloader-wrapper big">
    <div class="spinner-layer spinner-blue-only">
        <div class="circle-clipper left">
            <div class="circle"></div>
        </div><div class="gap-patch">
        <div class="circle"></div>
    </div><div class="circle-clipper right">
    <div class="circle"></div>
</div>
</div>
</div>
</div>
<!-- {% url 'updater:sessionIntouch' user.id %}
{% url 'updater:sessionUnitClub' user.id %} -->
</main>


<script type="text/javascript">$( document ).ready(function(){
$(".button-collapse").sideNav();
$('.modal').modal();
{% if messages %}
{% for message in messages %}
{% if 'info' in message.tags %}
Materialize.toast( '{{ message }}' , 3000) // 4000 is the duration of the toast
{%endif%}
{% if 'error' in message.tags %}
    $('#ErrorModal').modal('open');
    console.log('error')
{% endif %}
{% endfor %}
{% endif %}
});
</script>
<script type="text/javascript">
function hideSelection(){
$('.ErrorModal').modal('open');
$( "#selection" ).addClass( "hide" );
$( "#info" ).addClass( "hide" );
$( "#login" ).addClass( "hide" );
$( "#firstDivider" ).addClass( "hide" );
showSpinner();
}
function showSpinner(){
$( "#spin" ).addClass( "active" );
}
function hideSpinner(){
$( "#spin" ).removeClass( "active" );
}
</script>
{% endblock %}


{% block footer %}

{% endblock %}

updater/templates/updater/information.html
{% extends 'updater/base.html' %}
{% block navbar %}

{% endblock %}


{% block content %}
    <main>
    <div class="container">
    <p class="flow-text left-align">Mit <a href="/">Mary Kay Updater</a> kannst du deine Informationen auf der Unit Club <a href="www.unit-club.de"> Webseite</a> aktualisieren.</p>
    <p class="flow-text left-align">Dazu musst du dich sowohl bei Mary Kay Intouch als auch im Unit Club anmelden. Dazu klickst du auf die entsprechenden Buttons auf der Startseite, gibst deine Infromationen ein und klickst auf Login. Deine Anmeldedaten werden nicht auf dieser Seite gespeichert. Es wird lediglich deine Session gespeichert, die nach ein paar Stunden wieder abläuft. Danach musst du dich wieder neu einloggen.</p>

    <p class="flow-text left-align">Nachdem du dich erfolgreich eingeloggt hast, kannst du mit einem Knopfdruck die entsprechenden Bereiche des Unit Clubs aktualisieren. Das aktualisieren kann lange dauern, da die Dateien erst runter- und dann wieder hochgeladen werden müssen.</p>
    </div>
    <center>
    <a href="{% url 'updater:infoaccept' %}" class=' col s12 btn btn-large waves-effect indigo'>Verstanden</a>
    </center>
</main>
<div class="section"></div>

<script type="text/javascript">$( document ).ready(function(){
$(".button-collapse").sideNav();
});
</script>
{% endblock %}

{% block footer %}
{% endblock %}

updater/templates/updater/navbar.html
{% extends 'updater/base.html' %}